/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7TeoqgdpT2B
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Slider } from "@/components/ui/slider"

export function DistanceSlider({ value, setValue }: {
  value: number,
  setValue: (value: number) => void
}) {
  return (
    <div className="flex flex-col items-center justify-center text-white">
      <div className="max-w-md w-full space-y-4">
        <div className="flex items-center justify-between">
          <span className="">Unit Distance</span>
          <span className="">
            <span id="move-distance-value">{value}</span>{"\n"}
          </span>
        </div>
        <Slider
        onValueChange={(value) => setValue(value[0])}

          className="[&>span:first-child]:h-2 [&>span:first-child]:bg-gray-300 dark:[&>span:first-child]:bg-gray-700 [&_[role=slider]]:bg-gray-900 dark:[&_[role=slider]]:bg-gray-100 [&_[role=slider]]:w-4 [&_[role=slider]]:h-4 [&_[role=slider]]:border-0 [&>span:first-child_span]:bg-gray-900 dark:[&>span:first-child_span]:bg-gray-100 [&_[role=slider]:focus-visible]:ring-0 [&_[role=slider]:focus-visible]:ring-offset-0 [&_[role=slider]:focus-visible]:scale-105 [&_[role=slider]:focus-visible]:transition-transform"
          defaultValue={[value]}
          id="move-distance"
          max={100}
          min={0}
          step={10}
        />
      </div>
    </div>
  )
}
